
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'sandbox_datalake'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'sandbox_datalake'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  sandbox_datalake:
    bronze_to_silver:
      pokemon:
        final:
          showdown:
            sources:
              +pre-hook:
                - >
                  {% set source = var('source', 'dav') %}
                  {% set allowed_sources = ['dav', 'smogon'] %}
                  {% if source not in allowed_sources %}
                    {{ exceptions.raise_compiler_error("Invalid value for 'source': " ~ source ~ ". Allowed values: " ~ allowed_sources) }}
                  {% endif %}
              +post-hook:
                - >
                  {% set version = var('release_version', '-1') %}
                  {% set source = var('source', 'dav') %}
                  COPY {{ this }}
                  TO 's3://sandbox-datalake-silver/pokemon/showdown/{{ source }}/{{ version }}/{{ this.name }}.parquet'
                  (FORMAT PARQUET, COMPRESSION 'snappy')
      davlab:
        final:
          notion:
            +post-hook:
              - >
                {% set notion_date = var('notion_date', '-1') %}
                COPY {{ this }}
                TO 's3://sandbox-datalake-silver/davlab/notion/{{ notion_date }}/{{ this.name }}.parquet'
                (FORMAT PARQUET, COMPRESSION 'snappy')
    silver_to_gold:
      pokemon:
        final:
          showdown:
            sources:
              +pre-hook:
                - >
                  {% set source = var('source', 'dav') %}
                  {% set allowed_sources = ['dav', 'smogon'] %}
                  {% if source not in allowed_sources %}
                    {{ exceptions.raise_compiler_error("Invalid value for 'source': " ~ source ~ ". Allowed values: " ~ allowed_sources) }}
                  {% endif %}
              +post-hook:
                - >
                  {% set version = var('release_version', '-1') %}
                  {% set source = var('source', 'dav') %}
                  COPY {{ this }}
                  TO 's3://sandbox-datalake-gold/pokemon/showdown/{{ source }}/{{ version }}/{{ this.name }}.parquet'
                  (FORMAT PARQUET, COMPRESSION 'snappy')
            diff_dav_smogon:
              +post-hook:
                - >
                  {% set version = var('release_version', '-1') %}
                  COPY {{ this }}
                  TO 's3://sandbox-datalake-gold/pokemon/showdown/diff_dav_smogon/{{ version }}/{{ this.name }}.parquet'
                  (FORMAT PARQUET, COMPRESSION 'snappy')
      davlab:
        final:
          notion:
            +post-hook:
              - >
                {% set notion_date = var('notion_date', '-1') %}
                COPY {{ this }}
                TO 's3://sandbox-datalake-gold/davlab/notion/{{ notion_date }}/{{ this.name }}.parquet'
                (FORMAT PARQUET, COMPRESSION 'snappy')