{% set release_version = var('release_version') %}
{% set source = var('source', 'dav') %}

{% if source == 'dav' %}
    {% set input_path = 's3://sandbox-datalake-bronze/pokemon/showdown/dav/' ~ release_version ~ '/ability.json' %}
{% elif source == 'smogon' %}
    {% set input_path = 's3://sandbox-datalake-bronze/pokemon/showdown/smogon/ability.json' %}
{% endif %}

SELECT
    key AS key,
    isNonstandard AS is_nonstandard,
    flags AS flags,
    name AS name,
    rating AS rating,
    num AS num,
    "desc" AS description,
    shortDesc AS short_description,
    onModifyTypePriority AS on_modify_type_priority,
    onBasePowerPriority AS on_base_power_priority,
    onDamagingHitOrder AS on_damaging_hit_order,
    suppressWeather AS suppress_weather,
    onResidualOrder AS on_residual_order,
    onResidualSubOrder AS on_residual_sub_order,
    onAllyBasePowerPriority AS on_ally_base_power_priority,
    onCriticalHit AS on_critical_hit,
    onModifyAtkPriority AS on_modify_atk_priority,
    onModifySpAPriority AS on_modify_sp_a_priority,
    onSourceModifyAccuracyPriority AS on_source_modify_accuracy_priority,
    condition AS condition,
    onAnyBasePowerPriority AS on_any_base_power_priority,
    onDamagePriority AS on_damage_priority,
    onSourceBasePowerPriority AS on_source_base_power_priority,
    onAllyModifyAtkPriority AS on_ally_modify_atk_priority,
    onAllyModifySpDPriority AS on_ally_modify_spd_priority,
    onModifyDefPriority AS on_modify_def_priority,
    onDragOutPriority AS on_drag_out_priority,
    onSourceModifyAtkPriority AS on_source_modify_atk_priority,
    onSourceModifySpAPriority AS on_source_modify_sp_a_priority,
    onModifyWeightPriority AS on_modify_weight_priority,
    onTryHitPriority AS on_try_hit_priority,
    onModifyMovePriority AS on_modify_move_priority,
    onFractionalPriorityPriority AS on_fractional_priority_priority,
    onAnyInvulnerabilityPriority AS on_any_invulnerability_priority,
    onSourceModifyDamagePriority AS on_source_modify_damage_priority,
    onTryEatItemPriority AS on_try_eat_item_priority,
    onModifyAccuracyPriority AS on_modify_accuracy_priority,
    onAnyFaintPriority AS on_any_faint_priority,
    onFractionalPriority AS on_fractional_priority,
    onBeforeMovePriority AS on_before_move_priority,
    onAnyModifyAccuracyPriority AS on_any_modify_accuracy_priority,
    custom AS custom,
    onModifySpDPriority AS on_modify_spd_priority,
    onHitPriority AS on_hit_priority,
    onFoeBeforeMovePriority AS on_foe_before_move_priority
FROM read_json_auto(
    '{{ input_path }}',
    columns = {
        'key': 'VARCHAR',
        'isNonstandard': 'VARCHAR',
        'flags': 'JSON',
        'name': 'VARCHAR',
        'rating': 'DOUBLE',
        'num': 'BIGINT',
        'desc': 'VARCHAR',
        'shortDesc': 'VARCHAR',
        'onModifyTypePriority': 'BIGINT',
        'onBasePowerPriority': 'BIGINT',
        'onDamagingHitOrder': 'BIGINT',
        'suppressWeather': 'BOOLEAN',
        'onResidualOrder': 'BIGINT',
        'onResidualSubOrder': 'BIGINT',
        'onAllyBasePowerPriority': 'BIGINT',
        'onCriticalHit': 'BOOLEAN',
        'onModifyAtkPriority': 'BIGINT',
        'onModifySpAPriority': 'BIGINT',
        'onSourceModifyAccuracyPriority': 'BIGINT',
        'condition': 'JSON',
        'onAnyBasePowerPriority': 'BIGINT',
        'onDamagePriority': 'BIGINT',
        'onSourceBasePowerPriority': 'BIGINT',
        'onAllyModifyAtkPriority': 'BIGINT',
        'onAllyModifySpDPriority': 'BIGINT',
        'onModifyDefPriority': 'BIGINT',
        'onDragOutPriority': 'BIGINT',
        'onSourceModifyAtkPriority': 'BIGINT',
        'onSourceModifySpAPriority': 'BIGINT',
        'onModifyWeightPriority': 'BIGINT',
        'onTryHitPriority': 'BIGINT',
        'onModifyMovePriority': 'BIGINT',
        'onFractionalPriorityPriority': 'BIGINT',
        'onAnyInvulnerabilityPriority': 'BIGINT',
        'onSourceModifyDamagePriority': 'BIGINT',
        'onTryEatItemPriority': 'BIGINT',
        'onModifyAccuracyPriority': 'BIGINT',
        'onAnyFaintPriority': 'BIGINT',
        'onFractionalPriority': 'DOUBLE',
        'onBeforeMovePriority': 'BIGINT',
        'onAnyModifyAccuracyPriority': 'BIGINT',
        'custom': 'BOOLEAN',
        'onModifySpDPriority': 'BIGINT',
        'onHitPriority': 'BIGINT',
        'onFoeBeforeMovePriority': 'BIGINT'
    }
)