{% set release_version = var('release_version') %}
{% set source = var('source', 'dav') %}

{% if source == 'dav' %}
    {% set input_path = 's3://sandbox-datalake-bronze/pokemon/showdown/dav/' ~ release_version ~ '/move.json' %}
{% elif source == 'smogon' %}
    {% set input_path = 's3://sandbox-datalake-bronze/pokemon/showdown/smogon/move.json' %}
{% endif %}

SELECT
    key AS key,
    num AS num,
    accuracy AS accuracy,
    basePower AS base_power,
    category AS category,
    name AS name,
    pp AS pp,
    priority AS priority,
    flags AS flags,
    isZ AS is_z,
    critRatio AS crit_ratio,
    target AS target,
    type AS type,
    contestType AS contest_type,
    "desc" AS description,
    shortDesc AS short_description,
    isNonstandard AS is_nonstandard,
    stallingMove AS stalling_move,
    multiaccuracy AS multi_accuracy,
    selfSwitch AS self_switch,
    ignoreImmunity AS ignore_immunity,
    overrideOffensiveStat AS override_offensive_stat,
    maxMove AS max_move,
    recoil AS recoil,
    weather AS weather,
    ignoreDefensive AS ignore_defensive,
    ignoreEvasion AS ignore_evasion,
    forceSwitch AS force_switch,
    selfBoost AS self_boost,
    nonGhostTarget AS non_ghost_target,
    status AS status,
    smartTarget AS smart_target,
    damage AS damage,
    terrain AS terrain,
    hasSheerForce AS has_sheer_force,
    selfdestruct AS self_destruct,
    pseudoWeather AS pseudo_weather,
    onDamagePriority AS on_damage_priority,
    breaksProtect AS breaks_protect,
    secondaries AS secondaries,
    ohko AS ohko,
    willCrit AS will_crit,
    overrideOffensivePokemon AS override_offensive_pokemon,
    isMax AS is_max,
    ignoreAbility AS ignore_ability,
    slotCondition AS slot_condition,
    heal AS heal,
    realMove AS real_move,
    thawsTarget AS thaws_target,
    mindBlownRecoil AS mind_blown_recoil,
    overrideDefensiveStat AS override_defensive_stat,
    noPPBoosts AS no_pp_boosts,
    sleepUsable AS sleep_usable,
    tracksTarget AS tracks_target,
    stealsBoosts AS steals_boosts,
    struggleRecoil AS struggle_recoil

FROM read_json_auto(
    '{{ input_path }}',
    columns = {
        'key': 'VARCHAR',
        'num': 'BIGINT',
        'accuracy': 'JSON',
        'basePower': 'BIGINT',
        'category': 'VARCHAR',
        'name': 'VARCHAR',
        'pp': 'BIGINT',
        'priority': 'BIGINT',
        'flags': 'JSON',
        'isZ': 'VARCHAR',
        'critRatio': 'BIGINT',
        'target': 'VARCHAR',
        'type': 'VARCHAR',
        'contestType': 'VARCHAR',
        'desc': 'VARCHAR',
        'shortDesc': 'VARCHAR',
        'isNonstandard': 'VARCHAR',
        'stallingMove': 'BOOLEAN',
        'multiaccuracy': 'BOOLEAN',
        'selfSwitch': 'JSON',
        'ignoreImmunity': 'JSON',
        'overrideOffensiveStat': 'VARCHAR',
        'maxMove': 'JSON',
        'recoil': 'JSON',
        'weather': 'VARCHAR',
        'ignoreDefensive': 'BOOLEAN',
        'ignoreEvasion': 'BOOLEAN',
        'forceSwitch': 'BOOLEAN',
        'selfBoost': 'JSON',
        'nonGhostTarget': 'VARCHAR',
        'status': 'VARCHAR',
        'smartTarget': 'BOOLEAN',
        'damage': 'JSON',
        'terrain': 'VARCHAR',
        'hasSheerForce': 'BOOLEAN',
        'selfdestruct': 'VARCHAR',
        'pseudoWeather': 'VARCHAR',
        'onDamagePriority': 'BIGINT',
        'breaksProtect': 'BOOLEAN',
        'secondaries': 'JSON',
        'ohko': 'JSON',
        'willCrit': 'BOOLEAN',
        'overrideOffensivePokemon': 'VARCHAR',
        'isMax': 'JSON',
        'ignoreAbility': 'BOOLEAN',
        'slotCondition': 'VARCHAR',
        'heal': 'JSON',
        'realMove': 'VARCHAR',
        'thawsTarget': 'BOOLEAN',
        'mindBlownRecoil': 'BOOLEAN',
        'overrideDefensiveStat': 'VARCHAR',
        'noPPBoosts': 'BOOLEAN',
        'sleepUsable': 'BOOLEAN',
        'tracksTarget': 'BOOLEAN',
        'stealsBoosts': 'BOOLEAN',
        'struggleRecoil': 'BOOLEAN'
    }
)