{{ config(materialized = 'table') }}

{% set release_version = var('release_version') %}
{% set source = var('source') %}

SELECT
    key AS key,
    num AS num,
    name AS name,
    json_extract_string(types, '$[0]') AS type_1,
    json_extract_string(types, '$[1]') AS type_2,
    genderRatio.M::DOUBLE AS gender_ratio_m,
    genderRatio.F::DOUBLE AS gender_ratio_f,
    baseStats.hp::INTEGER AS hp,
    baseStats.atk::INTEGER AS atk,
    baseStats.def::INTEGER AS def,
    baseStats.spa::INTEGER AS spa,
    baseStats.spd::INTEGER AS spd,
    baseStats.spe::INTEGER AS spe,
    json_extract_string(abilities, '$.0') AS ability_0,
    json_extract_string(abilities, '$.1') AS ability_1,
    json_extract_string(abilities, '$.H') AS hidden_ability,
    heightm::DOUBLE AS height_m,
    weightkg::DOUBLE AS weight_kg,
    color AS color,
    evos AS evos,
    eggGroups AS egg_groups,
    tier AS tier,
    prevo AS prevo,
    evoLevel AS evo_level,
    otherFormes AS other_formes,
    formeOrder AS forme_order,
    canGigantamax AS can_gigantamax,
    baseSpecies AS base_species,
    forme AS forme,
    requiredItem AS required_item,
    changesFrom AS changes_from,
    isNonstandard AS is_nonstandard,
    evoCondition AS evo_condition,
    evoType AS evo_type,
    gender AS gender,
    gen AS gen,
    evoItem AS evo_item,
    evoRegion AS evo_region,
    mother AS mother,
    canHatch AS can_hatch,
    evoMove AS evo_move,
    tags AS tags,
    baseForme AS base_forme,
    cosmeticFormes AS cosmetic_formes,
    maxHP AS max_hp,
    requiredAbility AS required_ability,
    battleOnly AS battle_only,
    requiredMove AS required_move,
    requiredItems AS required_items,
    cannotDynamax AS cannot_dynamax,
    forceTeraType AS force_tera_type

FROM read_json_auto(
    's3://sandbox-datalake-bronze/pokemon/showdown/{{ source }}/{{ release_version }}/pokemon.json',
    columns = {
        'key': 'VARCHAR',
        'num': 'BIGINT',
        'name': 'VARCHAR',
        'types': 'JSON',
        'genderRatio': 'JSON',
        'baseStats': 'JSON',
        'abilities': 'JSON',
        'heightm': 'DOUBLE',
        'weightkg': 'DOUBLE',
        'color': 'VARCHAR',
        'evos': 'JSON',
        'eggGroups': 'JSON',
        'tier': 'VARCHAR',
        'prevo': 'VARCHAR',
        'evoLevel': 'BIGINT',
        'otherFormes': 'JSON',
        'formeOrder': 'JSON',
        'canGigantamax': 'VARCHAR',
        'baseSpecies': 'VARCHAR',
        'forme': 'VARCHAR',
        'requiredItem': 'VARCHAR',
        'changesFrom': 'VARCHAR',
        'isNonstandard': 'VARCHAR',
        'evoCondition': 'VARCHAR',
        'evoType': 'VARCHAR',
        'gender': 'VARCHAR',
        'gen': 'BIGINT',
        'evoItem': 'VARCHAR',
        'evoRegion': 'VARCHAR',
        'mother': 'VARCHAR',
        'canHatch': 'BOOLEAN',
        'evoMove': 'VARCHAR',
        'tags': 'JSON',
        'baseForme': 'VARCHAR',
        'cosmeticFormes': 'JSON',
        'maxHP': 'BIGINT',
        'requiredAbility': 'VARCHAR',
        'battleOnly': 'JSON',
        'requiredMove': 'VARCHAR',
        'requiredItems': 'JSON',
        'cannotDynamax': 'BOOLEAN',
        'forceTeraType': 'VARCHAR'
    }
)